site_name: 3270Connect
site_description: User Guide for the 3270Connect Command-Line Utility
site_author: 3270.io
copyright: "Â© 2023-2024 3270.io"
site_url: https://3270io.github.io/3270Connect
repo_url: https://github.com/3270io/3270Connect
edit_uri: edit/main/docs/

# Default directory for MkDocs output (GitHub Pages uses `gh-pages` branch)
site_dir: site

theme:
  name: material
  logo: assets/logo.png  # Ensure this file exists in the `docs/assets/` folder
  palette:
    primary: teal
  features:
    - navigation.instant
    - navigation.instant.progress
    - toc.integrate
    - navigation.expand
    - navigation.top
    - navigation.footer

nav:
  - Home: index.md
  - Installation: installation.md
  - Basic Usage: basic-usage.md
  - Workflow Actions: workflow.md
  - Advanced Features: advanced-features.md

plugins:
  - search
  - mkdocs-video:
      is_video: true
      video_autoplay: false

markdown_extensions:
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.highlight:
      use_pygments: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tasklist:
      clickable: true  # Corrected key
  - attr_list
  - def_list
  - pymdownx.snippets:
      base_path: docs
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - footnotes

extra:
  version: 1.0.7